import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import NavBarDesk from "@/ui/components/header/NavBar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:[ "400", "700"]
}); 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.webp'
  },
    keywords: ['houston-compass','bang'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" >
      <body
       className={`${geistSans.variable} ${geistMono.variable} font-geist-sans font-geist-mono`}
      >
        <NavBarDesk />
        {children}
      </body>
    </html>
  );
}
